### ISSUE TITLE
[DomainCell][ReviewEntriesAction]Unable to add a new sense to a semantic domain in the Review Entries tool

### ISSUE THREAD

**Issue by fuencui** [sillsdev/TheCombine#1906] opened 2023-02-16 16:49 UTC
Unable to add a new sense to a semantic domain when edit an entry at Review Entries tool in Data clean-up

**Comment by imnasnainaec** [comment] 2023-04-13 14:09
@fuencui Is this bug fixed? The issue is open, but it's Done in the project kanban and the associated pr is Merged.

**Closed** 2023-04-13 15:50 UTC
Labels: bug, goal: ReviewEntries
