### ISSUE TITLE
Unused code in backend WordIsUnique - Bug?

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#670] opened 2020-08-29 12:53 UTC
The following code is in WordApiServices:

https://github.com/sillsdev/TheCombine/blob/05b619192d2bd39fc95808adcdba7c867af24ee6/Backend/Services/WordApiServices.cs#L246-L280

`oldSenseIndex` and `newSenseIndex` are updated at the end of each of their successive loops, but overwritten to `0` at the start, so these lines of code don't do anything. Presumably they were mean to do something. Are we overwriting the same `Sense`s in these loops when we aren't supposed to?

This bug was detected by JetBrains Rider IDE.

**Comment by jmgrady** [comment] 2020-08-29 16:08
I am not sure that this is a bug.  I am not a JavaScript expert but I believe that the statement:
```
var newSense = 0;
```
is an initialization statement, not assignment.  This means that newSense is set to 0 when the memory is allocated and does not get reset to 0 on each iteration of the foreach loop.  Similarly, if it were written as:
```
var newSense;
```
it would be initialized to `undefined` but I do not believe that it would be reset to `undefined` with each iteration.

As I said, I am not a JavaScript expert so it would be good to check if this is the case with someone who knows the language well.

**Comment by imnasnainaec** [comment] 2020-08-31 15:41
Yes, this is a bug, but it only occurs in a specific situation, and the consequence is adding a semantic domain to the wrong sense.
To produce this bug:
* In Data Entry, navigate to a semantic domain (2. Person)
* Create a new entry (vern / gloss)
* Select DONE and navigate to a different domain (8. States)
* Type the vernacular of the entry you just created (vern) and select that entry when the dialog pops up
* In the second dialog, select "New sense for", type a new sense (gloss2), and press enter
* In the same semantic domain (8. States) type the same vernacular again (vern), but this time select "New entry for" in the first dialog
* Type the gloss of the second sense (gloss2) and press enter
  - This will trigger `foundDuplicateSense = true` in the buggy function under investigation
* Navigate to Review Entries and you will find that the first sense (gloss) now has two semantic domains, even though the duplicate submission was a duplicate of the second sense (gloss2)

**Comment by imnasnainaec** [comment] 2020-08-31 15:55
One reason this isn't often a problem is because the input `word`, being a new entry, can only have 1 sense. The update function within `WordIsUnique(Word word)` is currently useful now when the duplicate new entry is in a new semantic domain. The update will have additional utility should the `editedBy` property of `Word` be put to use.

**Closed** 2020-08-31 22:17 UTC
Labels: backend, maintenance
